#!/bin/bash
# Resolve container CLI: docker or podman (compose plugin or podman-compose).
# Sourced by bootstrap/wrapper — do not 'exit 0' on success.

set -euo pipefail

# Persist bind mounts across compose down/rebuild. Empty interpolation of
# ${HERMES_DATA_DIR}:/opt/data becomes :/opt/data; podman-compose treats that
# as an anonymous volume, which is discarded when the container is recreated.
# The image also declares VOLUME ["/opt/data"] as a fallback — never let
# compose fall through to it.

hermes_require_absolute_path() {
  local name="$1"
  local path="${2:-}"
  if [[ -z "$path" ]]; then
    printf 'ERROR: %s is empty. Compose would attach an anonymous VOLUME and wipe it on rebuild.\n' "$name" >&2
    return 1
  fi
  if [[ "$path" == *$'\n'* || "$path" == *$'\r'* ]]; then
    printf 'ERROR: %s must not contain a newline\n' "$name" >&2
    return 1
  fi
  if [[ "$path" == "/" ]]; then
    printf 'ERROR: %s must not be /\n' "$name" >&2
    return 1
  fi
  if [[ "$path" != /* ]]; then
    printf 'ERROR: %s must be an absolute path, got %q\n' "$name" "$path" >&2
    return 1
  fi
  # Keep compose .env / interpolation free of spaces, quotes, and metacharacters.
  if [[ ! "$path" =~ ^/[A-Za-z0-9._/-]+$ ]]; then
    printf 'ERROR: %s has unsafe characters (use [A-Za-z0-9._/-] only), got %q\n' "$name" "$path" >&2
    return 1
  fi
  if [[ "$path" == *'/..'* || "$path" == *'/./'* ]]; then
    printf 'ERROR: %s must not contain . or .. path segments\n' "$name" >&2
    return 1
  fi
}

hermes_require_numeric() {
  local name="$1"
  local val="${2:-}"
  if [[ ! "$val" =~ ^[0-9]+$ ]]; then
    printf 'ERROR: %s must be numeric, got %q\n' "$name" "$val" >&2
    return 1
  fi
}

# podman-compose applies project .env only for keys that are unset. An empty
# export (HERMES_DATA_DIR=) wins over .env and interpolates to :/opt/data.
hermes_unset_empty_compose_vars() {
  local k
  for k in HERMES_DATA_DIR HERMES_WORKSPACE_DIR HERMES_BUILD_CONTEXT \
    HERMES_UID HERMES_GID HERMES_DASHBOARD_PORT; do
    if [[ -z "${!k:-}" ]]; then
      unset "$k"
    fi
  done
}

hermes_prepare_persist_dirs() {
  hermes_require_absolute_path HERMES_DATA_DIR "${HERMES_DATA_DIR:-}" || return 1
  hermes_require_absolute_path HERMES_WORKSPACE_DIR "${HERMES_WORKSPACE_DIR:-}" || return 1
  mkdir -p "${HERMES_DATA_DIR}" "${HERMES_WORKSPACE_DIR}" || return 1
  # pwd -P needs traverse permission; rootless remap can leave the bind owned by
  # a subuid this user cannot cd into. Keep the absolute path in that case.
  if [[ -x "${HERMES_DATA_DIR}" ]]; then
    HERMES_DATA_DIR="$(cd "${HERMES_DATA_DIR}" && pwd -P)"
    hermes_require_absolute_path HERMES_DATA_DIR "$HERMES_DATA_DIR" || return 1
  fi
  if [[ -x "${HERMES_WORKSPACE_DIR}" ]]; then
    HERMES_WORKSPACE_DIR="$(cd "${HERMES_WORKSPACE_DIR}" && pwd -P)"
    hermes_require_absolute_path HERMES_WORKSPACE_DIR "$HERMES_WORKSPACE_DIR" || return 1
  fi
  export HERMES_DATA_DIR HERMES_WORKSPACE_DIR
}

hermes_write_compose_env() {
  local root="${1:?}"
  local envfile="${root}/.env"
  local build="${HERMES_BUILD_CONTEXT:-}"
  local port="${HERMES_DASHBOARD_PORT:-9120}"
  hermes_require_absolute_path HERMES_DATA_DIR "${HERMES_DATA_DIR:-}" || return 1
  hermes_require_absolute_path HERMES_WORKSPACE_DIR "${HERMES_WORKSPACE_DIR:-}" || return 1
  hermes_require_absolute_path HERMES_BUILD_CONTEXT "$build" || return 1
  hermes_require_numeric HERMES_UID "${HERMES_UID:-}" || return 1
  hermes_require_numeric HERMES_GID "${HERMES_GID:-}" || return 1
  hermes_require_numeric HERMES_DASHBOARD_PORT "$port" || return 1
  if [[ -d "$build" && -x "$build" ]]; then
    build="$(cd "$build" && pwd -P)"
    hermes_require_absolute_path HERMES_BUILD_CONTEXT "$build" || return 1
    export HERMES_BUILD_CONTEXT="$build"
  fi
  export HERMES_DASHBOARD_PORT="$port"
  local old_umask
  old_umask="$(umask)"
  umask 077
  # Quote values. podman-compose fills these from .env only when the key is unset
  # in the process environment — call hermes_unset_empty_compose_vars before compose.
  {
    printf '%s\n' '# Generated by hermes-assistant — compose interpolation only (paths/uids).'
    printf '%s\n' '# No secrets. Empty exported vars (HERMES_DATA_DIR=) override this file; unset them first.'
    printf 'HERMES_DATA_DIR="%s"\n' "$HERMES_DATA_DIR"
    printf 'HERMES_WORKSPACE_DIR="%s"\n' "$HERMES_WORKSPACE_DIR"
    printf 'HERMES_BUILD_CONTEXT="%s"\n' "$HERMES_BUILD_CONTEXT"
    printf 'HERMES_UID="%s"\n' "$HERMES_UID"
    printf 'HERMES_GID="%s"\n' "$HERMES_GID"
    printf 'HERMES_DASHBOARD_PORT="%s"\n' "$HERMES_DASHBOARD_PORT"
  } >"$envfile"
  umask "$old_umask"
}

_hermes_try_compose() {
  local cli="$1"
  local compose_cmd="$2"
  if command -v "$cli" >/dev/null 2>&1 && eval "$compose_cmd version" >/dev/null 2>&1; then
    export HERMES_CONTAINER_CLI="$cli"
    export HERMES_COMPOSE="$compose_cmd"
    return 0
  fi
  return 1
}

_fail() {
  echo "ERROR: need 'docker compose', 'podman compose', or 'podman-compose' on PATH" >&2
  echo "  PATH=${PATH}" >&2
  echo "  which podman: $(command -v podman 2>/dev/null || echo missing)" >&2
  echo "  which docker: $(command -v docker 2>/dev/null || echo missing)" >&2
  if [[ -n "${XDG_RUNTIME_DIR:-}" ]] && [[ -d "${XDG_RUNTIME_DIR}" ]]; then
    local xdg_uid
    xdg_uid="$(stat -c '%u' "${XDG_RUNTIME_DIR}" 2>/dev/null || echo '?')"
    if [[ "$xdg_uid" != "$(id -u)" ]]; then
      echo "  XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR} is owned by uid ${xdg_uid}, but you are uid $(id -u)" >&2
      echo "  Fix: do not use 'sudo -E' across users; use launch-with-host-env.sh" >&2
    fi
  fi
  if command -v podman >/dev/null 2>&1; then
    podman compose version 2>&1 >&2 || true
  fi
  return 1 2>/dev/null || exit 1
}

# Honor explicit overrides from migrate script / operator.
if [[ -n "${HERMES_CONTAINER_CLI:-}" && -n "${HERMES_COMPOSE:-}" ]]; then
  if eval "$HERMES_COMPOSE version" >/dev/null 2>&1; then
    return 0 2>/dev/null || exit 0
  fi
  echo "WARN: HERMES_COMPOSE=${HERMES_COMPOSE} failed version check; auto-detecting" >&2
  unset HERMES_CONTAINER_CLI HERMES_COMPOSE
fi

for dir in /usr/local/bin /usr/bin /bin /snap/bin \
  "${HOME}/.local/bin" "${HOME}/bin"; do
  [[ -d "$dir" ]] || continue
  case ":${PATH}:" in
    *":${dir}:"*) ;;
    *) PATH="${dir}:${PATH}" ;;
  esac
done
export PATH

_hermes_try_compose podman "podman-compose" && return 0 2>/dev/null || true
_hermes_try_compose podman "podman compose" && return 0 2>/dev/null || true
_hermes_try_compose docker "docker compose" && return 0 2>/dev/null || true
_hermes_try_compose docker "docker-compose" && return 0 2>/dev/null || true

# If sourced, return 1; if executed directly, exit 1.
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  _fail || return 1
else
  _fail || exit 1
fi
