#!/bin/bash
# Install systemd user autostart for Hermes Assistant (operator = bucephalus3).
#
# One-time setup:
#   1. source ~/.bashrc   # keys in your shell
#   2. sudo bash ~/hermes-assistant/scripts/install-autostart.sh
#
# This will:
#   - create config/env.secrets from your current shell (allowlisted names only)
#   - install passwordless sudo for run-as-hermes-privileged.sh
#   - enable linger + systemd --user unit hermes-assistant.service
#   - start the stack once

set -euo pipefail

OPERATOR_USER="${HERMES_OPERATOR_USER:-bucephalus3}"
OPERATOR_KIT="${HERMES_OPERATOR_KIT:-/home/${OPERATOR_USER}/hermes-assistant}"
TARGET_USER="${HERMES_TARGET_USER:-hermes}"
UNIT_SRC="${OPERATOR_KIT}/systemd/hermes-assistant.service"
PRIVILEGED="${OPERATOR_KIT}/scripts/run-as-hermes-privileged.sh"
ALLOWLIST="${OPERATOR_KIT}/config/env.allowlist"
SECRETS="${OPERATOR_KIT}/config/env.secrets"
SUDOERS_FILE="/etc/sudoers.d/hermes-assistant"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run: sudo bash $0" >&2
  echo "Tip: source ~/.bashrc in your shell first so keys can be copied into env.secrets." >&2
  exit 1
fi

CALLER="${SUDO_USER:-}"
if [[ -z "$CALLER" || "$CALLER" == "root" ]]; then
  CALLER="$OPERATOR_USER"
fi
CALLER_HOME="$(getent passwd "$CALLER" | cut -d: -f6)"
UNIT_DST="${CALLER_HOME}/.config/systemd/user/hermes-assistant.service"

[[ -d "$OPERATOR_KIT" ]] || { echo "Missing kit: $OPERATOR_KIT" >&2; exit 1; }
[[ -f "$UNIT_SRC" ]] || { echo "Missing unit: $UNIT_SRC" >&2; exit 1; }
[[ -f "$PRIVILEGED" ]] || { echo "Missing helper: $PRIVILEGED" >&2; exit 1; }
[[ -f "$ALLOWLIST" ]] || { echo "Missing allowlist: $ALLOWLIST" >&2; exit 1; }

chmod 0755 "$PRIVILEGED" \
  "${OPERATOR_KIT}/scripts/launch-with-host-env.sh" \
  "${OPERATOR_KIT}/scripts/install-autostart.sh"
# Privileged helper must stay root-owned so hermes cannot rewrite the sudo target.
chown root:root "$PRIVILEGED"
chmod 0755 "$PRIVILEGED"

# --- env.secrets: copy allowlisted values from caller's environment ---
# shellcheck source=export-allowlisted-env.sh
source "${OPERATOR_KIT}/scripts/export-allowlisted-env.sh"

# Prefer sudo -E so allowlisted keys from the invoking shell are visible here.
if [[ ! -f "$SECRETS" ]]; then
  echo "# Generated by install-autostart.sh — mode 600, do not commit" > "$SECRETS"
  mapfile -t names < <(hermes_read_allowlist_names "$ALLOWLIST" || true)
  wrote=0
  for name in "${names[@]}"; do
    val="${!name-}"
    if [[ -z "$val" && -n "${SUDO_USER:-}" ]]; then
      val="$(sudo -u "$CALLER" bash -lc "printf '%s' \"\${$name-}\"" 2>/dev/null || true)"
    fi
    printf '%s=%s\n' "$name" "$val" >> "$SECRETS"
    [[ -n "$val" ]] && wrote=$((wrote + 1))
  done
  chown "$CALLER:$CALLER" "$SECRETS"
  chmod 600 "$SECRETS"
  echo "Created ${SECRETS} (${wrote} non-empty value(s))."
  if [[ "$wrote" -eq 0 ]]; then
    echo "WARN: all secret values empty." >&2
    echo "  Re-run after: source ~/.bashrc && sudo -E bash $0" >&2
    echo "  Or edit ${SECRETS} manually, then: systemctl --user restart hermes-assistant.service" >&2
  fi
else
  chown "$CALLER:$CALLER" "$SECRETS"
  chmod 600 "$SECRETS"
  echo "Keeping existing ${SECRETS}"
fi

# --- sudoers: passwordless privileged helper only ---
cat > "$SUDOERS_FILE" <<EOF
# Hermes Assistant autostart — narrow NOPASSWD for operator → root helper
# Installed by ${OPERATOR_KIT}/scripts/install-autostart.sh
${CALLER} ALL=(root) NOPASSWD: ${PRIVILEGED}
EOF
chmod 440 "$SUDOERS_FILE"
visudo -cf "$SUDOERS_FILE"

# --- linger (user systemd at boot without login) ---
loginctl enable-linger "$CALLER"
loginctl enable-linger "$TARGET_USER"

# --- user unit ---
install -o "$CALLER" -g "$CALLER" -d "${CALLER_HOME}/.config/systemd/user"
install -o "$CALLER" -g "$CALLER" -m 0644 "$UNIT_SRC" "$UNIT_DST"

# Reload / enable / start as the operator user
CALLER_UID="$(id -u "$CALLER")"
export XDG_RUNTIME_DIR="/run/user/${CALLER_UID}"
if [[ ! -d "$XDG_RUNTIME_DIR" ]]; then
  echo "WARN: ${XDG_RUNTIME_DIR} missing — log in once as ${CALLER} or reboot after linger." >&2
fi

runuser -u "$CALLER" -- env XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
  systemctl --user daemon-reload
runuser -u "$CALLER" -- env XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
  systemctl --user enable hermes-assistant.service

echo ""
echo "Starting hermes-assistant.service once..."
if runuser -u "$CALLER" -- env XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
  systemctl --user start hermes-assistant.service; then
  runuser -u "$CALLER" -- env XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
    systemctl --user --no-pager status hermes-assistant.service || true
else
  echo "WARN: start failed — check: journalctl --user -u hermes-assistant.service" >&2
  echo "  and that ${SECRETS} has real keys." >&2
fi

echo ""
echo "OK: autostart installed."
echo "  systemctl --user status hermes-assistant.service"
echo "  systemctl --user restart hermes-assistant.service"
echo "  journalctl --user -u hermes-assistant.service -f"
echo "Secrets file: ${SECRETS} (chmod 600)"
